containers = {"食盒", "皮腰带", "布袋", "粗磁大碗", "大葫芦", "清水葫芦", "牛皮酒袋", "花雕酒袋", "酒瓶", "野菜汤碗", "水壶"}

foods = {"烤鸭:kaoya", "三套鸭:santao ya", "烤鸡腿:jitui", "五香茶叶蛋:spicy egg", "烤玉米:corn", "火腿:huo tui",
         "水晶肴肉:shuijing yaorou", "太湖银鱼:taihu yinyu", "包子:baozi", "扬州炒饭:fried rice", "红烧狗肉:gou rou",
         "红烧鸡翅膀:chicken wing", "水蜜桃:tao", "荷叶饼:heye bing", "过桥黑鱼:guoqiao heiyu", "高粱米饭:rice",
         "岁寒三友:suihan sanyou","荷花办蒸鸡:hehua ji", "小米粥:xiaomi zhou", "薄皮包子:baozi", "桃花糕:taohua gao",
         "蜜饯火腿", "菠菜羊肉抓饭", "香炙牛肉条", "冰镇香梨", "葡萄酒", "东坡肉", "西湖醋鱼", "百果油包", "龙井虾仁",
         "叫化童鸡", "桂花鲜栗羹", "夹心荸荠", "牡丹生菜", "琉璃茄子", "麻辣豆腐", "拔丝山药", "翡翠甜饼", "红菱",
         "葡萄", "桂圆", "鱼饺", "鱼饼", "鱼卷", "熟牛肉", "过桥米线", "叶儿粑", "蛇羹", "烤全羊"}

drinks = {"饱腹玉:baofu yu", "汽锅鸡:qiguo ji", "香茶:tea", "酥油茶:tea", "野菜汤碗:soup", "牛皮酒袋:jiudai", "花雕酒袋:jiudai",
          "酒瓶:jiuping", "粗磁大碗:wan", "大葫芦:da hulu", "清水葫芦:qingshui hulu", "水壶:shui hu", "鲜菱荷叶羹:heye geng",
          "酒瓶:huadiao", "酒瓶:nuerhong", "酒瓶:zhuangyuan hong", "酒瓶:zhuye qing", "酒瓶:longyan jiu", "酒瓶:xiangxue jiu"}

drugs = {
            js = {"养精丹:yangjing dan", "首乌精:shouwu jing", "九花玉露丸:yulu wan", "续命八丹:xuming badan", "精神丹药:jingshen danyao"},
            qx = {"百草丹:baicao dan", "九花玉露丸:yulu wan", "三黄宝蜡丸:sanhuang wan", "续命八丹:xuming badan", "气血丹药:qixue danyao"},
        }

items = {
    ["金蛇剑:jinshe jian"]           = {name = "金蛇剑",          id = "jinshe jian",       group = "weapon",     type = "sword",     count = 1,   price = {0},   spare = "雷乘剑:leicheng jian",   treasure = true},
    ["重阳剑:chongyang jian"]        = {name = "重阳剑",          id = "chongyang jian",    group = "weapon",     type = "sword",     count = 1,   price = {0},   spare = "雷乘剑:leicheng jian",   treasure = true},
    ["白虹剑:baihong jian"]          = {name = "白虹剑",          id = "baihong jian",      group = "weapon",     type = "sword",     count = 1,   price = {0},   spare = "雷乘剑:leicheng jian",   treasure = true},
    ["白龙剑:bailong jian"]          = {name = "白龙剑",          id = "bailong jian",      group = "weapon",     type = "sword",     count = 1,   price = {0},   spare = "雷乘剑:leicheng jian",   treasure = true},
    ["碧水剑:bishui jian"]           = {name = "碧水剑",          id = "bishui jian",       group = "weapon",     type = "sword",     count = 1,   price = {0},   spare = "雷乘剑:leicheng jian",   treasure = true},
    ["玄铁重剑:xuantie jian"]        = {name = "玄铁重剑",        id = "xuantie jian",      group = "weapon",     type = "sword",     count = 1,   price = {0},   spare = "雷乘剑:leicheng jian",   treasure = true},
    ["倚天剑:yitian jian"]           = {name = "倚天剑",          id = "yitian jian",       group = "weapon",     type = "sword",     count = 1,   price = {0},   spare = "雷乘剑:leicheng jian",   treasure = true},
    ["真武剑:zhenwu sword"]          = {name = "真武剑",          id = "zhenwu sword",      group = "weapon",     type = "sword",     count = 1,   price = {0},   spare = "雷乘剑:leicheng jian",   treasure = true},
    ["巨阙剑:juque jian"]            = {name = "巨阙剑",          id = "juque jian",        group = "weapon",     type = "sword",     count = 1,   price = {0},   spare = "雷乘剑:leicheng jian",   treasure = true},
    ["工布剑:gongbu jian"]           = {name = "工布剑",          id = "gongbu jian",       group = "weapon",     type = "sword",     count = 1,   price = {0},   spare = "雷乘剑:leicheng jian",   treasure = true},
    ["鱼肠剑:yuchang jian"]          = {name = "鱼肠剑",          id = "yuchang jian",      group = "weapon",     type = "sword",     count = 1,   price = {0},   spare = "雷乘剑:leicheng jian",   treasure = true},
    ["胜邪剑:shengxie jian"]         = {name = "胜邪剑",          id = "shengxie jian",     group = "weapon",     type = "sword",     count = 1,   price = {0},   spare = "雷乘剑:leicheng jian",   treasure = true},
    ["纯钧剑:chunjun jian"]          = {name = "纯钧剑",          id = "chunjun jian",      group = "weapon",     type = "sword",     count = 1,   price = {0},   spare = "雷乘剑:leicheng jian",   treasure = true},
    ["龙渊剑:longyuan jian"]         = {name = "龙渊剑",          id = "longyuan jian",     group = "weapon",     type = "sword",     count = 1,   price = {0},   spare = "雷乘剑:leicheng jian",   treasure = true},
    ["湛泸剑:zhanlu jian"]           = {name = "湛泸剑",          id = "zhanlu jian",       group = "weapon",     type = "sword",     count = 1,   price = {0},   spare = "雷乘剑:leicheng jian",   treasure = true},
    ["太阿剑:taie jian"]             = {name = "太阿剑",          id = "taie jian",         group = "weapon",     type = "sword",     count = 1,   price = {0},   spare = "雷乘剑:leicheng jian",   treasure = true},
    ["干将剑:ganjiang jian"]         = {name = "干将剑",          id = "ganjiang jian",     group = "weapon",     type = "sword",     count = 1,   price = {0},   spare = "雷乘剑:leicheng jian",   treasure = true},
    ["莫邪剑:moye jian"]             = {name = "莫邪剑",          id = "moye jian",         group = "weapon",     type = "sword",     count = 1,   price = {0},   spare = "雷乘剑:leicheng jian",   treasure = true},
    ["七星剑:qixing jian"]           = {name = "七星剑",          id = "qixing jian",       group = "weapon",     type = "sword",     count = 1,   price = {0},   spare = "雷乘剑:leicheng jian",   treasure = true},
    ["黑剑:hei jian"]                = {name = "黑剑",            id = "hei jian",          group = "weapon",     type = "sword",     count = 1,   price = {0},   spare = "雷乘剑:leicheng jian",   treasure = true},
    ["观日剑:guanri jian"]           = {name = "观日剑",          id = "guanri jian",       group = "weapon",     type = "sword",     count = 1,   price = {0},   spare = "雷乘剑:leicheng jian",   treasure = true},
    ["影之哀伤:yingzhi aishang"]     = {name = "影之哀伤",        id = "yingzhi aishang",   group = "weapon",     type = "sword",     count = 1,   price = {0},   spare = "雷乘剑:leicheng jian",   treasure = true},
    ["紫薇软剑:ziwei ruanjian"]      = {name = "紫薇软剑",        id = "ziwei ruanjian",    group = "weapon",     type = "sword",     count = 1,   price = {0},   spare = "雷乘剑:leicheng jian",   treasure = true},
    ["玉箫:yu xiao"]                 = {name = "玉箫",            id = "yu xiao",           group = "weapon",     type = "sword",     count = 1,   price = {0},   spare = "雷乘剑:leicheng jian",   treasure = true},
    ["钢剑:gangjian"]                = {name = "钢剑",            id = "gangjian",          group = "weapon",     type = "sword",     count = 1,   price = {0, 300, 300},      place = {2400, 2717, 2566},           get = {"get sword", "buy", "buy"}},
    ["长剑:changjian"]               = {name = "长剑",            id = "changjian",         group = "weapon",     type = "sword",     count = 1,   price = {0, 0},             place = {873, 376},                   get = {"get", "get"}},
    ["竹剑:zhu jian"]                = {name = "竹剑",            id = "zhu jian",          group = "weapon",     type = "sword",     count = 1,   price = {0},                place = {873},                        get = {"get"}},
    ["短剑:duanjian"]                = {name = "短剑",            id = "duanjian",          group = "weapon",     type = "sword",     count = 1,   price = {0},                place = {873},                        get = {"get"}},
    ["软剑:ruanjian"]                = {name = "软剑",            id = "ruanjian",          group = "weapon",     type = "sword",     count = 1,   price = {},                 place = {},                           get = {}},
    ["玉剑:yu jian"]                 = {name = "玉剑",            id = "yu jian",           group = "weapon",     type = "sword",     count = 1,   price = {10000},            place = {1894},                       get = {"buy"}},
    ["青钢剑:qinggang jian"]         = {name = "青钢剑",          id = "qinggang jian",     group = "weapon",     type = "sword",     count = 1,   price = {0},                place = {1535},                       get = {"kill feng xifan"}},
    ["雷乘剑:leicheng jian"]         = {name = "雷乘剑",          id = "leicheng jian",     group = "weapon",     type = "sword",     count = 1,   price = {5000, 5000},       place = {2717, 2401},                 get = {"buy", "buy"}},
    ["冰王笛:bingwang di"]           = {name = "冰王笛",          id = "bingwang di",       group = "weapon",     type = "sword",     count = 1,   price = {100000, 100000},   place = {2717, 2401},                 get = {"buy", "buy"}},
    ["竹箫:zhu xiao"]                = {name = "竹箫",            id = "zhu xiao",          group = "weapon",     type = "sword",     count = 1,   price = {0, 0, 0},          place = {935, 1793, 1741},            get = {"get", "get", "get"}},
    ["铁箫:tie xiao"]                = {name = "铁箫",            id = "tie xiao",          group = "weapon",     type = "sword",     count = 1,   price = {0, 0},             place = {1793, 1741},                 get = {"get", "get"}},
    ["自铸之剑:personal sword"]      = {name = "自铸之剑",        id = "personal sword",    group = "weapon",     type = "sword",     count = 1,   price = {0},    spare = "雷乘剑:leicheng jian",   place = {58},     get = {"ask ji kang about 寻回"},   reserve = true},
    ["八咫镜:bazhi jing"]            = {name = "八咫镜",          id = "bazhi jing",        group = "weapon",     type = "hammer",    count = 1,   price = {0},   spare = "铜轮:fa lun",            treasure = true},
    ["金轮:jin lun"]                 = {name = "金轮",            id = "jin lun",           group = "weapon",     type = "hammer",    count = 5,   price = {0},   spare = "铜轮:fa lun",            treasure = true,   stack = true},
    ["炎魔锤:yanmo"]                 = {name = "炎魔锤",          id = "yanmo",             group = "weapon",     type = "hammer",    count = 1,   price = {0},   spare = "打铁锤:datie chui",      treasure = true},
    ["铁锤:hammer"]                  = {name = "铁锤",            id = "hammer",            group = "weapon",     type = "hammer",    count = 1,   price = {0, 150},           place = {2400, 833},                  get = {"get hammer", "buy"}},
    ["打铁锤:datie chui"]            = {name = "打铁锤",          id = "datie chui",        group = "weapon",     type = "hammer",    count = 1,   price = {5000, 5000},       place = {2717, 2401},                 get = {"buy", "buy"}},
    ["铜轮:fa lun"]                  = {name = "铜轮",            id = "fa lun",            group = "weapon",     type = "hammer",    count = 1,   price = {1000, 1000},       place = {2717, 2401},                 get = {"buy", "buy"},   stack = true},
    ["法轮:fa lun"]                  = {name = "法轮",            id = "fa lun",            group = "weapon",     type = "hammer",    count = 1,   price = {0, 0, 0, 1000},    place = {423, 428, 437, 438},   get = {"get", "get", "get", "buy"}, stack = true},
    ["颅钵:lu bo"]                   = {name = "颅钵",            id = "lu bo",             group = "weapon",     type = "hammer",    count = 1,   price = {100},              place = {438},                        get = {"buy"}},
    ["法铃:fa ling"]                 = {name = "法铃",            id = "fa ling",           group = "weapon",     type = "hammer",    count = 1,   price = {0, 10},            place = {428, 438},                   get = {"get", "buy"}},
    ["铁锹:tie qiao"]                = {name = "铁锹",            id = "tie qiao",          group = "weapon",     type = "hammer",    count = 1,   price = {150},              place = {615},                        get = {"buy"}},
    ["自铸之锤:personal hammer"]     = {name = "自铸之锤",        id = "personal hammer",   group = "weapon",     type = "hammer",    count = 1,   price = {0},   spare = "打铁锤:datie chui",     place = {58},       get = {"ask ji kang about 寻回"},   reserve = true},
    ["水火虬龙棍:shuihuo qiulong"]   = {name = "水火虬龙棍",      id = "shuihuo qiulong",   group = "weapon",     type = "club",      count = 1,   price = {0},   spare = "盘龙棍:panlong gun",     treasure = true},
    ["铁棍:tiegun"]                  = {name = "铁棍",            id = "tiegun",            group = "weapon",     type = "club",      count = 1,   price = {0, 100},           place = {2400, 1256},                 get = {"get club", "buy"}},
    ["盘龙棍:panlong gun"]           = {name = "盘龙棍",          id = "panlong gun",       group = "weapon",     type = "club",      count = 1,   price = {5000, 5000},       place = {2717, 2401},                 get = {"buy", "buy"}},
    ["齐眉棍:qimei gun"]             = {name = "齐眉棍",          id = "qimei gun",         group = "weapon",     type = "club",      count = 1,   price = {150},              place = {2717},                       get = {"buy"}},
    ["折凳:zhedeng"]                 = {name = "折凳",            id = "zhedeng",           group = "weapon",     type = "club",      count = 1,   price = {5000},             place = {2401},                       get = {"buy"}},
    ["自铸之棍:personal club"]       = {name = "自铸之棍",        id = "personal club",     group = "weapon",     type = "club",      count = 1,   price = {0},   spare = "盘龙棍:panlong gun",       place = {58},    get = {"ask ji kang about 寻回"},   reserve = true},
    ["妇好斧:fuhao fu"]              = {name = "妇好斧",          id = "fuhao fu",          group = "weapon",     type = "axe",       count = 1,   price = {0},   spare = "开山斧:kaishan fu",       treasure = true},
    ["黄金斧:huangjin fu"]           = {name = "黄金斧",          id = "huangjin fu",       group = "weapon",     type = "axe",       count = 1,   price = {0},   spare = "开山斧:kaishan fu",       treasure = true},
    ["宣花斧:xuanhua fu"]            = {name = "宣花斧",          id = "xuanhua fu",        group = "weapon",     type = "axe",       count = 1,   price = {0},   spare = "开山斧:kaishan fu",       treasure = true},
    ["大斧头:da futou"]              = {name = "大斧头",          id = "da futou",          group = "weapon",     type = "axe",       count = 1,   price = {0, 250},           place = {2400, 1023},                 get = {"get axe", "buy"}},
    ["开山斧:kaishan fu"]            = {name = "开山斧",          id = "kaishan fu",        group = "weapon",     type = "axe",       count = 1,   price = {5000, 5000},       place = {2717, 2401},                 get = {"buy", "buy"}},
    ["板斧:ban fu"]                  = {name = "板斧",            id = "ban fu",            group = "weapon",     type = "axe",       count = 1,   price = {},                 place = {},                           get = {}},
    ["小铁斧:xiao tiefu"]            = {name = "小铁斧",          id = "xiao tiefu",        group = "weapon",     type = "axe",       count = 1,   price = {200},              place = {1023},                       get = {"buy"}},
    ["自铸之斧:personal axe"]        = {name = "自铸之斧",        id = "personal axe",      group = "weapon",     type = "axe",       count = 1,   price = {0},   spare = "开山斧:kaishan fu",        place = {58},     get = {"ask ji kang about 寻回"},   reserve = true},
    ["血刀:xue dao"]                 = {name = "血刀",            id = "xue dao",           group = "weapon",     type = "blade",     count = 1,   price = {0},   spare = "青龙刀:qinglong dao",     treasure = true},
    ["屠龙刀:tulong dao"]            = {name = "屠龙刀",          id = "tonglong dao",      group = "weapon",     type = "blade",     count = 1,   price = {0},   spare = "青龙刀:qinglong dao",     treasure = true},
    ["伏魔刀:fumo dao"]              = {name = "伏魔刀",          id = "fumo dao",          group = "weapon",     type = "blade",     count = 1,   price = {0},   spare = "青龙刀:qinglong dao",     treasure = true},
    ["枯骨刀:kugu dao"]              = {name = "枯骨刀",          id = "kugu dao",          group = "weapon",     type = "blade",     count = 1,   price = {0},   spare = "青龙刀:qinglong dao",     treasure = true},
    ["玄古刀:xuangu dao"]            = {name = "玄古刀",          id = "xuangu dao",        group = "weapon",     type = "blade",     count = 1,   price = {0},   spare = "青龙刀:qinglong dao",     treasure = true},
    ["鬼头刀:guitou dao"]            = {name = "鬼头刀",          id = "guitou dao",        group = "weapon",     type = "blade",     count = 1,   price = {0},   spare = "青龙刀:qinglong dao",     treasure = true},
    ["金刀:jin dao"]                 = {name = "金刀",            id = "jin dao",           group = "weapon",     type = "blade",     count = 1,   price = {0},   spare = "青龙刀:qinglong dao",     treasure = true},
    ["绿波香露刀:xianglu dao"]       = {name = "绿波香露刀",      id = "xianglu dao",       group = "weapon",     type = "blade",     count = 1,   price = {0},   spare = "青龙刀:qinglong dao",     treasure = true},
    ["鳄嘴剪:ezui jian"]             = {name = "鳄嘴剪",          id = "ezui jian",         group = "weapon",     type = "blade",     count = 1,   price = {0},   spare = "青龙刀:qinglong dao",     treasure = true},
    ["冷艳锯:lengyan ju"]            = {name = "冷艳锯",          id = "lengyan ju",        group = "weapon",     type = "blade",     count = 1,   price = {0},   spare = "青龙刀:qinglong dao",     treasure = true},
    ["钢刀:blade"]                   = {name = "钢刀",            id = "blade",             group = "weapon",     type = "blade",     count = 1,   price = {0, 200, 200},      place = {2400, 2717, 2566},           get = {"get blade", "buy", "buy"}},
    ["青龙刀:qinglong dao"]          = {name = "青龙刀",          id = "qinglong dao",      group = "weapon",     type = "blade",     count = 1,   price = {5000, 5000},       place = {2717, 2401},                 get = {"buy", "buy"}},
    ["菜刀:cai dao"]                 = {name = "菜刀",            id = "cai dao",           group = "weapon",     type = "blade",     count = 1,   price = {30, 30, 30},       place = {1023, 833, 1256},            get = {"buy", "buy", "buy"}},
    ["竹刀:zhu dao"]                 = {name = "竹刀",            id = "zhu dao",           group = "weapon",     type = "blade",     count = 1,   price = {0},                place = {376},                        get = {"get"}},
    ["戒刀:jie dao"]                 = {name = "戒刀",            id = "jie dao",           group = "weapon",     type = "blade",     count = 1,   price = {},                 place = {},                           get = {}},
    ["柳叶刀:liuyedao"]              = {name = "柳叶刀",          id = "liuyedao",          group = "weapon",     type = "blade",     count = 1,   price = {0},                place = {376},                        get = {"get"}},
    ["自铸之刀:personal blade"]      = {name = "自铸之刀",        id = "personal blade",    group = "weapon",     type = "blade",     count = 1,   price = {0},   spare = "青龙刀:qinglong dao",      place = {58},    get = {"ask ji kang about 寻回"},   reserve = true},
    ["黑龙鞭:heilong bian"]          = {name = "黑龙鞭",          id = "heilong bian",      group = "weapon",     type = "whip",      count = 1,   price = {0},   spare = "打神鞭:dashen bian",      treasure = true},
    ["毒龙鞭:dulong bian"]           = {name = "毒龙鞭",          id = "dulong bian",       group = "weapon",     type = "whip",      count = 1,   price = {0},   spare = "打神鞭:dashen bian",      treasure = true},
    ["鳄尾鞭:ewei bian"]             = {name = "鳄尾鞭",          id = "ewei bian",         group = "weapon",     type = "whip",      count = 1,   price = {0},   spare = "打神鞭:dashen bian",      treasure = true},
    ["金铃索:jinling suo"]           = {name = "金铃索",          id = "jinling suo",       group = "weapon",     type = "whip",      count = 1,   price = {0},   spare = "铃丝索:lingsi suo",       treasure = true},
    ["长鞭:changbian"]               = {name = "长鞭",            id = "changbian",         group = "weapon",     type = "whip",      count = 1,   price = {0, 200},           place = {2400, 2717},                 get = {"get whip", "buy"}},
    ["打神鞭:dashen bian"]           = {name = "打神鞭",          id = "dashen bian",       group = "weapon",     type = "whip",      count = 1,   price = {5000, 5000},       place = {2717, 2401},                 get = {"buy", "buy"}},
    ["玉尘:yu zhu"]                  = {name = "玉尘",            id = "yu zhu",            group = "weapon",     type = "whip",      count = 1,   price = {5000},             place = {1894},                       get = {"buy"}},
    ["铃丝索:lingsi suo"]            = {name = "铃丝索",          id = "lingsi suo",        group = "weapon",     type = "whip",      count = 1,   price = {},                 place = {},                           get = {}},
    ["自铸之鞭:personal whip"]       = {name = "自铸之鞭",        id = "personal whip",     group = "weapon",     type = "whip",      count = 1,   price = {0},   spare = "打神鞭:dashen bian",       place = {58},    get = {"ask ji kang about 寻回"},   reserve = true},
    ["火尖枪:huojianqiang"]          = {name = "火尖枪",          id = "huojianqiang",      group = "weapon",     type = "pike",      count = 1,   price = {0},   spare = "狼牙枪:langya qiang",     treasure = true},
    ["长枪:chang qiang"]             = {name = "长枪",            id = "chang qiang",       group = "weapon",     type = "pike",      count = 1,   price = {0, 200},           place = {2400, 2717},                 get = {"get pike", "buy"}},
    ["狼牙枪:langya qiang"]          = {name = "狼牙枪",          id = "langya qiang",      group = "weapon",     type = "pike",      count = 1,   price = {5000, 5000},       place = {2717, 2401},                 get = {"buy", "buy"}},
    ["自铸之枪:personal pike"]       = {name = "自铸之枪",        id = "personal pike",     group = "weapon",     type = "pike",      count = 1,   price = {0},   spare = "狼牙枪:langya qiang",      place = {58},    get = {"ask ji kang about 寻回"},   reserve = true},
    ["金花杖:jinhua zhang"]          = {name = "金花杖",          id = "jinhua zhang",      group = "weapon",     type = "staff",     count = 1,   price = {0},   spare = "修罗杖:xiuluo zhang",     treasure = true},
    ["九环锡杖:nine-ring staff"]     = {name = "九环锡杖",        id = "nine-ring staff",   group = "weapon",     type = "staff",     count = 1,   price = {0},   spare = "修罗杖:xiuluo zhang",     treasure = true},
    ["禅杖:chan zhang"]              = {name = "禅杖",            id = "chan zhang",        group = "weapon",     type = "staff",     count = 1,   price = {0},                place = {2400},                       get = {"get staff"}},
    ["修罗杖:xiuluo zhang"]          = {name = "修罗杖",          id = "xiuluo zhang",      group = "weapon",     type = "staff",     count = 1,   price = {5000, 5000},       place = {2717, 2401},                 get = {"buy", "buy"}},
    ["怪蛇杖:guai shezhang"]         = {name = "怪蛇杖",          id = "guai shezhang",     group = "weapon",     type = "staff",     count = 1,   price = {0},                place = {2400},                       get = {"ask ouyang ke about job"}},
    ["灵蛇杖:lingshe zhang"]         = {name = "灵蛇杖",          id = "lingshe zhang",     group = "weapon",     type = "staff",     count = 1,   price = {},                 place = {},                           get = {}},
    ["钢杖:gangzhang"]               = {name = "钢杖",            id = "gangzhang",         group = "weapon",     type = "staff",     count = 1,   price = {250},              place = {2717},                       get = {"buy"}},
    ["玉杖:yu zhang"]                = {name = "玉杖",            id = "yu zhang",          group = "weapon",     type = "staff",     count = 1,   price = {8500},             place = {1894},                       get = {"buy"}},
    ["法杵:fa chu"]                  = {name = "法杵",            id = "fa chu",            group = "weapon",     type = "staff",     count = 1,   price = {0, 100},           place = {428, 438},                   get = {"get", "buy"}},
    ["自铸之杖:personal staff"]      = {name = "自铸之杖",        id = "personal staff",    group = "weapon",     type = "staff",     count = 1,   price = {0},   spare = "修罗杖:xiuluo zhang",      place = {58},     get = {"ask ji kang about 寻回"},   reserve = true},
    ["金箍棒:jingu bang"]            = {name = "金箍棒",          id = "jingu bang",        group = "weapon",     type = "stick",     count = 1,   price = {0},   spare = "金刚棒:jingang bang",     treasure = true},
    ["金刚棒:jingang bang"]          = {name = "金刚棒",          id = "jingang bang",      group = "weapon",     type = "stick",     count = 1,   price = {5000, 5000},       place = {2717, 2401},                 get = {"buy", "buy"}},
    ["铜棒:tong bang"]               = {name = "铜棒",            id = "tong bang",         group = "weapon",     type = "stick",     count = 1,   price = {0},                place = {2400},                       get = {"get stick"}},
    ["竹棒:zhu bang"]                = {name = "竹棒",            id = "zhu bang",          group = "weapon",     type = "stick",     count = 1,   price = {0},                place = {1118},                       get = {"get"}},
    ["黄竹棒:huang zhubang"]         = {name = "黄竹棒",          id = "huang zhubang",     group = "weapon",     type = "stick",     count = 1,   price = {0},                place = {1118},                       get = {"get"}},
    ["铁棒:tie bang"]                = {name = "铁棒",            id = "tie bang",          group = "weapon",     type = "stick",     count = 1,   price = {350},              place = {1023},                       get = {"buy"}},
    ["木棒:mu bang"]                 = {name = "木棒",            id = "mu bang",           group = "weapon",     type = "stick",     count = 1,   price = {50},               place = {837},                        get = {"buy"}},
    ["钢棒:gang bang"]               = {name = "钢棒",            id = "gang bang",         group = "weapon",     type = "stick",     count = 1,   price = {400},              place = {1256},                       get = {"buy"}},
    ["自铸之棒:personal stick"]      = {name = "自铸之棒",        id = "personal stick",    group = "weapon",     type = "stick",     count = 1,   price = {0},   spare = "金刚棒:jingang bang",      place = {58},     get = {"ask ji kang about 寻回"},   reserve = true},
    ["孔雀翎:kongque ling"]          = {name = "孔雀翎",          id = "kongque ling",      group = "weapon",     type = "stroke",    count = 1,   price = {0},   spare = "封喉笔:feng houbi",       treasure = true},
    ["判官笔:panguan bi"]            = {name = "判官笔",          id = "panguan bi",        group = "weapon",     type = "stroke",    count = 1,   price = {0},                place = {2400},                       get = {"get stroke"}},
    ["封喉笔:feng houbi"]            = {name = "封喉笔",          id = "feng houbi",        group = "weapon",     type = "stroke",    count = 1,   price = {5000, 5000},       place = {2717, 2401},                 get = {"buy", "buy"}},
    ["自铸之笔:personal stroke"]     = {name = "自铸之笔",        id = "personal stroke",   group = "weapon",     type = "stroke",    count = 1,   price = {0},                place = {58},                         get = {"ask ji kang about 寻回"}},
    ["双钩:shuang gou"]              = {name = "双钩",            id = "shuang gou",        group = "weapon",     type = "hook",      count = 1,   price = {0, 250},           place = {2400, 2717},                 get = {"get hook", "buy"}},
    ["离别钩:libie gou"]             = {name = "离别钩",          id = "libie gou",         group = "weapon",     type = "hook",      count = 1,   price = {5000, 5000},       place = {2717, 2401},                 get = {"buy", "buy"}},
    ["自铸之钩:personal hook"]       = {name = "自铸之钩",        id = "personal hook",     group = "weapon",     type = "hook",      count = 1,   price = {0},   spare = "封喉笔:feng houbi",        place = {58},    get = {"ask ji kang about 寻回"},   reserve = true},
    ["圣阿武契的战书:santa glove"]   = {name = "圣阿武契的战书",  id = "santa glove",       group = "equpment",   type = "hand",      count = 1,   price = {5000, 5000},       place = {2717, 2401},                 get = {"buy", "buy"}},
    ["金刚罩:jingang zhao"]          = {name = "金刚罩",          id = "jingang zhao",      group = "equpment",   type = "body",      count = 1,   price = {0},   spare = "党卫军衣:nasos uniforms", treasure = true},
    ["软猬甲:ruanwei jia"]           = {name = "软猬甲",          id = "ruanwei jia",       group = "equpment",   type = "body",      count = 1,   price = {0},   spare = "党卫军衣:nasos uniforms", treasure = true},
    ["黄金甲:huangjin jia"]          = {name = "黄金甲",          id = "huangjin jia",      group = "equpment",   type = "body",      count = 1,   price = {0},   spare = "党卫军衣:nasos uniforms", treasure = true},
    ["乌蚕衣:wucan yi"]              = {name = "乌蚕衣",          id = "wucan yi",          group = "equpment",   type = "body",      count = 1,   price = {0},   spare = "党卫军衣:nasos uniforms", treasure = true},
    ["党卫军衣:nasos uniforms"]      = {name = "党卫军衣",        id = "nasos uniforms",    group = "equpment",   type = "body",      count = 1,   price = {5000, 5000},       place = {2717, 2401},                 get = {"buy", "buy"}},
    ["铁甲:tie jia"]                 = {name = "铁甲",            id = "tie jia",           group = "equpment",   type = "body",      count = 1,   price = {2500, 2500},       place = {2717, 2566},                 get = {"buy", "buy"}},
    ["铁甲:armor"]                   = {name = "铁甲",            id = "armor",             group = "equpment",   type = "body",      count = 1,   price = {0, 0, 0, 0},       place = {1070, 1071, 1072, 1074},     get = {"kill wei shi", "kill wei shi", "kill wei shi", "kill wei shi"}},
    ["环状甲:huanzhuang jia"]        = {name = "环状甲",          id = "huanzhuang jia",    group = "equpment",   type = "body",      count = 1,   price = {1500},             place = {1926},                       get = {}},
    ["板状甲:banzhuang jia"]         = {name = "板状甲",          id = "banzhuang jia",     group = "equpment",   type = "body",      count = 1,   price = {2000},             place = {1926},                       get = {}},
    ["锁子甲:suozi jia"]             = {name = "锁子甲",          id = "suozi jia",         group = "equpment",   type = "body",      count = 1,   price = {3000},             place = {1926},                       get = {}},
    ["云龙铠甲:yunlong kaijia"]      = {name = "云龙铠甲",        id = "yunlong kaijia",    group = "equpment",   type = "body",      count = 1,   price = {250000},           place = {1926},                       get = {}},
    ["唐猊铠甲:tangni kaijia"]       = {name = "唐猊铠甲",        id = "tangni kaijia",     group = "equpment",   type = "body",      count = 1,   price = {150000},           place = {1926},                       get = {}},
    ["高筒钢靴:gaotong gangxue"]     = {name = "高筒钢靴",        id = "gaotong gangxue",   group = "equpment",   type = "foot",      count = 1,   price = {10000},            place = {1926},                       get = {}},
    ["紫缎面鞋子:shoes"]             = {name = "紫缎面鞋子",      id = "shoes",             group = "equpment",   type = "foot",      count = 1,   price = {0},                place = {995},                        get = {"kill ding busan"}},
    ["臂钏:bi chuan"]                = {name = "臂钏",            id = "bi chuan",          group = "equpment",   type = "arm",       count = 1,   price = {0},                place = {1854},                       get = {"kill yangzong", "kill zhuoma"},   reserve = true},
    ["骷髅冠:kulou guan"]            = {name = "骷髅冠",          id = "kulou guan",        group = "equpment",   type = "head",      count = 1,   price = {500},              place = {438},                        get = {"buy"}},
    ["面罩:mian zhao"]              = {name = "面罩",           id = "mian zhao",          group = "equpment",   type = "head",      count = 1,   price = {0},                place = {1067, 1248},                 get = {"kill mengmian ren", "kill mengmian ren"}},
    ["人头链:rentou lian"]           = {name = "人头链",          id = "rentou lian",       group = "equpment",   type = "neck",      count = 1,   price = {150},              place = {438},                        get = {"buy"}},
    ["金项链:golden necklace"]       = {name = "金项链",          id = "golden necklace",   group = "equpment",   type = "neck",      count = 1,   price = {1500},             place = {992},                        get = {"buy"}},
    ["白银项链:silver necklace"]     = {name = "白银项链",        id = "silver necklace",   group = "equpment",   type = "neck",      count = 1,   price = {4000},             place = {992},                        get = {"buy"}},
    ["琥珀项链:amber necklace"]      = {name = "琥珀项链",        id = "amber necklace",    group = "equpment",   type = "neck",      count = 1,   price = {5000},             place = {992},                        get = {"buy"}},
    ["象牙项链:ivory necklace"]      = {name = "象牙项链",        id = "ivory necklace",    group = "equpment",   type = "neck",      count = 1,   price = {6000},             place = {992},                        get = {"buy"}},
    ["珍珠项链:pearl necklace"]      = {name = "珍珠项链",        id = "pearl necklace",    group = "equpment",   type = "neck",      count = 1,   price = {7000},             place = {992},                        get = {"buy"}},
    ["钻石项链:diamond necklace"]    = {name = "钻石项链",        id = "diamond necklace",  group = "equpment",   type = "neck",      count = 1,   price = {28000},            place = {992},                        get = {"buy"}},
    ["白金戒指:platinum ring"]       = {name = "白金戒指",        id = "platinum ring",     group = "equpment",   type = "finger",    count = 1,   price = {9900},             place = {992},                        get = {"buy"}},
    ["珍珠戒指:pearl ring"]          = {name = "珍珠戒指",        id = "pearl ring",        group = "equpment",   type = "finger",    count = 1,   price = {5500},             place = {992},                        get = {"buy"}},
    ["象牙戒指:ivory ring"]          = {name = "象牙戒指",        id = "ivory ring",        group = "equpment",   type = "finger",    count = 1,   price = {4500},             place = {992},                        get = {"buy"}},
    ["碧玉戒指:jade ring"]           = {name = "碧玉戒指",        id = "jade ring",         group = "equpment",   type = "finger",    count = 1,   price = {6500},             place = {992},                        get = {"buy"}},
    ["银戒指:silver ring"]           = {name = "银戒指",          id = "silver ring",       group = "equpment",   type = "finger",    count = 1,   price = {3500},             place = {992},                        get = {"buy"}},
    ["铁戒指:iron ring"]             = {name = "铁戒指",          id = "iron ring",         group = "equpment",   type = "finger",    count = 1,   price = {2500},             place = {992},                        get = {"buy"}},
    ["钻石戒指:diamond ring"]        = {name = "钻石戒指",        id = "diamond ring",      group = "equpment",   type = "finger",    count = 1,   price = {18000},            place = {992},                        get = {"buy"}},
    ["琥珀耳饰:amber earring"]       = {name = "琥珀耳饰",        id = "amber earring",     group = "equpment",   type = "ear",       count = 1,   price = {3000},             place = {992},                        get = {"buy"}},
    ["象牙耳饰:ivory earring"]       = {name = "象牙耳饰",        id = "ivory earring",     group = "equpment",   type = "ear",       count = 1,   price = {5000},             place = {992},                        get = {"buy"}},
    ["碧玉耳饰:jade earring"]        = {name = "碧玉耳饰",        id = "jade earring",      group = "equpment",   type = "ear",       count = 1,   price = {7000},             place = {992},                        get = {"buy"}},
    ["珍珠耳饰:pearl earring"]       = {name = "珍珠耳饰",        id = "pearl earring",     group = "equpment",   type = "ear",       count = 1,   price = {6000},             place = {992},                        get = {"buy"}},
    ["钻石耳饰:diamond earring"]     = {name = "钻石耳饰",        id = "diamond earring",   group = "equpment",   type = "ear",       count = 1,   price = {24000},            place = {992},                        get = {"buy"}},
    ["铜钱:coin"]                  = {name = "铜钱",         id = "coin",                   group = "misc",   type = "money",   stack = true,   reserve = true},
    ["白银:silver"]                = {name = "白银",         id = "silver",                 group = "misc",   type = "money",   stack = true,   reserve = true},
    ["黄金:gold"]                  = {name = "黄金",         id = "gold",                   group = "misc",   type = "money",   stack = true,   reserve = true},
    ["续命八丹:xuming badan"]      = {name = "续命八丹",     id = "xuming badan",           group = "misc",   type = "drug",    price = {},     place = {},       get = {},      reserve = true},
    ["九花玉露丸:yulu wan"]        = {name = "九花玉露丸",   id = "yulu wan",            group = "misc",   type = "drug",    price = {},     place = {},       get = {},      reserve = true},
    ["三黄宝蜡丸:sanhuang wan"]       = {name = "三黄宝蜡丸",   id = "sanhuang wan",        group = "misc",   type = "drug",    price = {},     place = {},       get = {},      reserve = true},
    ["百草丹:baicao dan"]          = {name = "百草丹",       id = "baicao dan",              group = "misc",   type = "drug",    price = {},     place = {},       get = {},      reserve = true},
    ["首乌精:shouwu jing"]         = {name = "首乌精",       id = "shouwu jing",            group = "misc",   type = "drug",    price = {},     place = {},       get = {},      reserve = true},
    ["养精丹:yangjing dan"]         = {name = "养精丹",       id = "yangjing dan",          group = "misc",   type = "drug",    price = {1000},  place = {1024},   get = {"buy"}, reserve = true},
    ["人参果:renshen guo"]         = {name = "人参果",       id = "renshen guo",            group = "misc",   type = "drug",    price = {0},     place = {},       get = {},      reserve = true},
    ["雪莲:xuelian"]               = {name = "雪莲",         id = "xuelian",                group = "misc",   type = "drug",    price = {0},     place = {3102},   get = {"get"}, reserve = true},
    ["大血藤:da xueteng"]          = {name = "大血藤",       id = "da xueteng",             group = "misc",   type = "drug",    price = {},     place = {},       get = {},      reserve = true},
    ["内力丹药:neili danyao"]      = {name = "内力丹药",     id = "neili danyao",           group = "misc",   type = "drug",    price = {0},     place = {},       get = {},      reserve = true},
    ["经脉丹药:jingmai danyao"]    = {name = "经脉丹药",     id = "jingmai danyao",         group = "misc",   type = "drug",    price = {0},     place = {},       get = {},      reserve = true},
    ["气血丹药:qixue danyao"]      = {name = "气血丹药",     id = "qixue danyao",           group = "misc",   type = "drug",    price = {},     place = {},       get = {},      reserve = true},
    ["精神丹药:jingshen danyao"]   = {name = "精神丹药",     id = "jingshen danyao",        group = "misc",   type = "drug",    price = {},     place = {},       get = {},      reserve = true},
    ["精力丹药:jingli danyao"]     = {name = "精力丹药",     id = "jingli danyao",          group = "misc",   type = "drug",    price = {},     place = {},       get = {},      reserve = true},
    ["力量丹药:liliang danyao"]    = {name = "力量丹药",     id = "liliang danyao",         group = "misc",   type = "drug",    price = {0},     place = {},       get = {},      reserve = true},
    ["灵活丹药:linghuo danyao"]    = {name = "灵活丹药",     id = "linghuo danyao",         group = "misc",   type = "drug",    price = {0},     place = {},       get = {},      reserve = true},
    ["智慧丹药:zhihui danyao"]     = {name = "智慧丹药",     id = "zhihui danyao",          group = "misc",   type = "drug",    price = {0},     place = {},       get = {},      reserve = true},
    ["体质丹药:tizhi danyao"]      = {name = "体质丹药",     id = "tizhi danyao",           group = "misc",   type = "drug",    price = {0},     place = {},       get = {},      reserve = true},
    ["防御丹药:fangyu danyao"]     = {name = "防御丹药",     id = "fangyu danyao",          group = "misc",   type = "drug",    price = {0},     place = {},       get = {},      reserve = true},
    ["攻击丹药:gongji danyao"]     = {name = "攻击丹药",     id = "gongji danyao",          group = "misc",   type = "drug",    price = {0},     place = {},       get = {},      reserve = true},
    ["《玄门内功心法》:xuanmen xinfa"]        = {name = "《玄门内功心法》",       id = "xuanmen xinfa",         group = "misc",       type = "book",    price = {},         place = {},             get = {},                            reserve = true},
    ["《神照经》:shenzhao jing"]             = {name = "《神照经》",             id = "shenzhao jing",         group = "misc",       type = "book",    price = {0},        place = {},             get = {},                          reserve = true},
    ["《九阳神功残篇》:jiuyang canpian"]      = {name = "《九阳神功残篇》",       id = "jiuyang canpian",       group = "misc",       type = "book",    price = {},        place = {},             get = {},   reserve = true},
    ["龙象般若经:longxiang jing"]            = {name = "《龙象般若经》",         id = "longxiang jing",        group = "misc",       type = "book",    price = {0},        place = {1853},         get = {"get longxiang jing"},       reserve = true},
    ["《龙象般若经》手抄本:longxiang jing"]   = {name = "《龙象般若经手抄本》",   id = "longxiang jing",        group = "misc",       type = "book",    price = {0},        place = {436},          get = {"ask jiumozhi about 龙象经"},   reserve = true},
    ["《紫霞秘笈》:zixia miji"]              = {name = "《紫霞秘笈》",           id = "zixia miji",           group = "misc",       type = "book",    price = {0},        place = {885},          get = {"search bed"},   reserve = true},
    ["《金蛇秘笈》:jinshe miji"]             = {name = "《金蛇秘笈》",           id = "jinshe miji",           group = "misc",       type = "book",    price = {0},        place = {3186},         get = {},                          reserve = true},
    ["易经《杂卦篇》:jing"]                  = {name = "易经《杂卦篇》",         id = "jing",                  group = "misc",       type = "book",    price = {0},        place = {1741},         get = {"get"}},
    ["易经《系辞篇》:jing"]                   = {name = "易经《系辞篇》",         id = "jing",                  group = "misc",       type = "book",    price = {0},        place = {1793},         get = {"get"}},
    ["《孔雀王咒经》:fo jing"]                = {name = "《孔雀王咒经》",         id = "fo jing",               group = "misc",       type = "book",    price = {0, 200},   place = {426, 438},     get = {"get", "buy"}},
    ["《金光明经》:fo jing"]                  = {name = "《金光明经》",           id = "fo jing",               group = "misc",       type = "book",    price = {0},        place = {442},          get = {"get"}},
    ["《持世陀罗尼经》:shu"]                  = {name = "《持世陀罗尼经》",       id = "shu",                   group = "misc",       type = "book",    price = {},         place = {},             get = {}},
    ["《八埋茶刹罗经》:shu"]                  = {name = "《八埋茶刹罗经》",       id = "shu",                   group = "misc",       type = "book",    price = {},         place = {},             get = {}},
    ["北冥秘籍:beiming miji"]                 = {name = "北冥秘籍",               id = "beiming miji",          group = "misc",       type = "book",    price = {0},        place = {3164},         get = {"find miji"},                      reserve = true},
    ["纯阳神通功秘诀:shentong mijue"]         = {name = "纯阳神通功秘诀",         id = "shentong mijue",        group = "misc",       type = "book",    price = {},        place = {},             get = {},                                 reserve = true},
    ["百战余生:baizhan yusheng"]              = {name = "百战余生",               id = "baizhan yusheng",       group = "misc",       type = "book",    price = {},        place = {},             get = {},                                 reserve = true},
    ["金蛇锥:jinshe zhui"]                    = {name = "金蛇锥",                 id = "jinshe zhui",           group = "misc",    price = {0},               place = {3186},                       get = {"get"},                            reserve = true,   stack = true},
    ["金花:jinhua biao"]                      = {name = "金花",                   id = "jinhua biao",           group = "misc",    price = {},               place = {},                           get = {},                                 reserve = true,   stack = true},
    ["铁焰令:tieyan ling"]                    = {name = "铁焰令",                 id = "tieyan ling",           group = "misc",    price = {0},               place = {584},                        get = {"ask leng qian about 铁焰令"},     reserve = true},
    ["天鹰令:tianying ling"]                  = {name = "天鹰令",                 id = "tianying ling",         group = "misc",    price = {0},               place = {1241},                       get = {"ask li tianheng about 天鹰令"},   reserve = true},
    ["黑木令:heimu ling"]                     = {name = "黑木令",                 id = "heimu ling",            group = "misc",    price = {0},               place = {2758},                       get = {"ask jia bu about 黑木令"},        reserve = true},
    ["侍卫腰牌:yaopai"]                       = {name = "侍卫腰牌",               id = "yaopai",                group = "misc",    price = {0},               place = {2286},                       get = {"ask duo long about 腰牌"},        reserve = true},
    ["皮帽:wanshou pimao"]                    = {name = "皮帽",                   id = "wanshou pimao",         group = "misc",    price = {0},               place = {2731},                       get = {"ask guan jia about 皮帽"},        reserve = true},
    ["炼心石:lianxin shi"]                    = {name = "炼心石",                 id = "lianxin shi",           group = "misc",    price = {},               place = {},                           get = {},                                 reserve = true},
    ["饱腹玉:baofu yu"]                       = {name = "饱腹玉",                 id = "baofu yu",              group = "misc",    price = {},               place = {},                           get = {},                                 reserve = true},
    ["铁八卦:tie bagua"]                      = {name = "铁八卦",                 id = "tie bagua",             group = "misc",    price = {1920},            place = {1278},                       get = {"buy"}},
    ["花雕酒袋:jiudai"]                       = {name = "花雕酒袋",               id = "jiudai",                group = "misc",    price = {120, 120},        place = {280, 947},                   get = {"buy", "buy"}},
    ["牛皮酒袋:jiudai"]                       = {name = "牛皮酒袋",               id = "jiudai",                group = "misc",    price = {50},              place = {948},                        get = {"buy"}},
    ["食盒:shi he"]                           = {name = "食盒",                   id = "shi he",                group = "misc",    price = {50},              place = {1019},                       get = {"buy"}},
    ["汽锅鸡:qiguo ji"]                       = {name = "汽锅鸡",                 id = "qiguo ji",              group = "misc",    price = {120},             place = {280},                        get = {"buy"}},
    ["皮腰带:yao dai"]                        = {name = "皮腰带",                 id = "yao dai",               group = "misc",    price = {0},               place = {376},                        get = {"ask jing feng about 皮腰带"}},
    ["火折:fire"]                             = {name = "火折",                   id = "fire",                  group = "misc",    price = {100},             place = {1019},                       get = {"buy"}},
    ["火折:huo zhe"]                          = {name = "火折",                   id = "huo zhe",               group = "misc",    price = {100, 100},        place = {837, 615},                   get = {"buy", "buy"}},
    ["绳子:sheng zi"]                         = {name = "绳子",                   id = "sheng zi",              group = "misc",    price = {30, 30},          place = {837, 615},                   get = {"buy", "buy"}},
    ["武学残卷:wuxue canjuan"]                = {name = "武学残卷",               id = "wuxue canjuan",         group = "misc",    price = {0},               place = {},                           get = {},                                 reserve = true,     stack = true},
    ["鸠摩智的武学笔记:wuxue biji"]           = {name = "鸠摩智的武学笔记",       id = "wuxue biji",            group = "misc",     price = {},                place = {},                           get = {},                                 reserve = true},
    ["乌金矿:wujin kuang"]                    = {name = "乌金矿",                 id = "wujin kuang",           group = "misc",   reserve = true},
    ["玄铁矿:xuantie kuang"]                  = {name = "玄铁矿",                 id = "xuantie kuang",         group = "misc",   reserve = true},
    ["紫金矿:zijin kuang"]                    = {name = "紫金矿",                 id = "zijin kuang",           group = "misc",   reserve = true},
    ["黑黝矿:heiyou kuang"]                   = {name = "黑黝矿",                 id = "heiyou kuang",          group = "misc",   reserve = true},
    ["黑铁矿:heitie kuang"]                   = {name = "黑铁矿",                 id = "heitie kuang",          group = "misc",   reserve = true},
    ["赤铜矿:chitong kuang"]                  = {name = "乌金矿",                 id = "chitong kuang",         group = "misc",   reserve = true},
    ["精铁矿:jingtie kuang"]                  = {name = "乌金矿",                 id = "jingtie kuang",         group = "misc",   reserve = true},
    ["洗心革面丹:chongzhi danyao"]            = {name = "洗心革面丹",             id = "chongzhi danyao",       group = "misc",   reserve = true},
    ["念珠:nian zhu"]                         = {name = "念珠",                   id = "nian zhu",              group = "misc",   reserve = true},
    ["布袋:bu dai"]                           = {name = "布袋",                   id = "bu dai",                group = "misc",   reserve = true},
    ["药方:yao fang"]                         = {name = "药方",                   id = "yao fang",              group = "misc",   reserve = true},
    ["八步夺命散:dm-san"]                     = {name = "八步夺命散",             id = "dm-san",                group = "misc",   reserve = true},
    ["清螺健步散:ql-san"]                     = {name = "清螺健步散",             id = "ql-san",                group = "misc",   reserve = true},
    ["九转大还丹:jz-dan"]                     = {name = "九转大还丹",             id = "jz-dan",                group = "misc",   reserve = true},
    ["雪莲玉蟾丸:yc-wan"]                     = {name = "雪莲玉蟾丸",             id = "yc-wan",                group = "misc",   reserve = true},
    ["紫晶罗刹粉:zj-san"]                     = {name = "紫晶罗刹粉",             id = "zj-san",                group = "misc",   reserve = true},
    ["茯苓:fuling"]                           = {name = "茯苓",                   id = "fuling",                group = "misc",   reserve = true},
    ["巴豆:ba dou"]                           = {name = "巴豆",                   id = "ba dou",                group = "misc",   reserve = true},
    ["生地:shengdi"]                          = {name = "生地",                   id = "shengdi",               group = "misc",   reserve = true},
    ["田七:tianqi"]                           = {name = "田七",                   id = "tianqi",                group = "misc",   reserve = true},
    ["豹胎:bao tai"]                          = {name = "豹胎",                   id = "bao tai",               group = "misc",   reserve = true},
    ["菊梗:jugeng"]                           = {name = "菊梗",                   id = "jugeng",                group = "misc",   reserve = true},
    ["川贝:chuanbei"]                         = {name = "川贝",                   id = "chuanbei",              group = "misc",   reserve = true},
    ["黄连:huanglian"]                        = {name = "黄连",                   id = "huanglian",             group = "misc",   reserve = true},
    ["牛黄:niuhuang"]                         = {name = "牛黄",                   id = "niuhuang",              group = "misc",   reserve = true},
    ["人参:renshen"]                          = {name = "人参",                   id = "renshen",               group = "misc",   reserve = true},
    ["雄黄:xionghuang"]                       = {name = "雄黄",                   id = "xionghuang",            group = "misc",   reserve = true},
    ["鲨胆:shadan"]                           = {name = "鲨胆",                   id = "shadan",                group = "misc",   reserve = true},
    ["熊胆:xiongdan"]                         = {name = "熊胆",                   id = "xiongdan",              group = "misc",   reserve = true},
    ["金银花:jinyin hua"]                     = {name = "金银花",                 id = "jinyin hua",            group = "misc",   reserve = true},
    ["枸枳子:gouzhi zi"]                      = {name = "枸枳子",                 id = "gouzhi zi",             group = "misc",   reserve = true},
    ["藏红花:zanghonghua"]                    = {name = "藏红花",                 id = "zanghonghua",           group = "misc",   reserve = true},
    ["何首乌:heshouwu"]                       = {name = "何首乌",                 id = "heshouwu",              group = "misc",   reserve = true},
}