return {{[ [[invalid_linji-zhuang_zhixin]] ] = {2},[ [[valid_shachang-dianbing_powerup]] ] = {3},[ [[valid_huntian-qigong_powerup]] ] = {4},[ [[invalid_huntian-qigong_powerup]] ] = {5},[ [[valid_linji-zhuang_fengyun]] ] = {6},[ [[valid_beiming-shengong_shield]] ] = {7},[ [[invalid_linji-zhuang_daxiao]] ] = {8},[ [[invalid_bitao-xuangong_yixing]] ] = {9},[ [[valid_huntian-qigong_shengang]] ] = {10},[ [[faint]] ] = {11},[ [[alive]] ] = {12},[ [[qishang]] ] = {13},[ [[invalid_yunu-xinjing_suxin]] ] = {14},[ [[valid_linji-zhuang_daxiao]] ] = {15},[ [[valid_xuantian-wuji_wuji]] ] = {16},[ [[valid_shachang-dianbing_charge]] ] = {17},[ [[valid_bitao-xuangong_yixing]] ] = {18},[ [[valid_yunu-xinjing_suxin]] ] = {19},[ [[invalid_lengyue-shengong_yue]] ] = {20},[ [[die]] ] = {21},[ [[invalid_dulong-dafa_powerup]] ] = {22},[ [[valid_dulong-dafa_powerup]] ] = {23},[ [[invalid_shachang-dianbing_powerup]] ] = {24},[ [[invalid_beiming-shengong_shield]] ] = {25},[ [[valid_linji-zhuang_zhixin]] ] = {26},[ [[invalid_ask_ping]] ] = {27},[ [[valid_lengyue-shengong_yue]] ] = {28},[ [[invalid_huntian-qigong_shengang]] ] = {29},[ [[invalid_shachang-dianbing_charge]] ] = {30},[ [[invalid_linji-zhuang_fengyun]] ] = {31},[ [[invalid_xuantian-wuji_wuji]] ] = {32},[ [[valid_force_yun]] ] = {33},},
{[1] = [[state.buff["linji-zhuang_zhixin"] = nil]],[2] = [[状态记录]],[3] = {34},[4] = 1,[5] = [[^你体内已积过多浊气，似乎领悟力又归于寻常。$]],},
{[1] = [[state.buff["shachang-dianbing_powerup"] = true]],[2] = [[状态记录]],[3] = {35},[4] = 1,[5] = [[^你大声战嚎，声势震天，让人又看到了那个千军万马中的大将军。$]],},
{[1] = [[state.buff["huntian-qigong_powerup"] = true]],[2] = [[状态记录]],[3] = {36},[4] = 1,[5] = [[^你微一凝神，运起混天气功，全身骨节发出一阵爆豆般的声响ⅵ$]],},
{[1] = [[state.buff["huntian-qigong_powerup"] = nil]],[2] = [[状态记录]],[3] = {37},[4] = 1,[5] = [[^你的混天气功运行完毕，将内力收回丹田。$]],},
{[1] = [[state.buff["linji-zhuang_fengyun"] = true]],[2] = [[状态记录]],[3] = {38},[4] = 1,[5] = [[^你暗运风云两庄，心思浮云飘空之悠闲缓慢，默想狂风荡地之迅速紧急，$|^你此时四肢百骸真气鼓荡，不必再次运功。$]],},
{[1] = [[state.buff["beiming-shengong_shield"] = true]],[2] = [[状态记录]],[3] = {39},[4] = 1,[5] = [[^你双手平举过顶，运起北冥真气，全身笼罩在劲气之中！$]],},
{[1] = [[state.buff["linji-zhuang_daxiao"] = nil]],[2] = [[状态记录]],[3] = {40},[4] = 1,[5] = [[^你行大小二庄已久，又恢复了原有精气。$]],},
{[1] = [[state.buff["bitao-xuangong_yixing"] = nil]],[2] = [[状态记录]],[3] = {41},[4] = 1,[5] = [[^你只觉真气运转不畅，不得不放慢步法，调息吐纳。$]],},
{[1] = [[state.buff["huntian-qigong_shengang"] = true]],[2] = [[状态记录]],[3] = {42},[4] = 1,[5] = [[^你凝神默然运功，不一会手上的\S+似乎发出淡淡光辉！$|^你已在使用混天神罡了！$]],},
{[1] = [[profile.activity = '昏迷']],[2] = [[状态记录]],[3] = {43},[4] = 1,[5] = [[^你的眼前一黑，接著什么也不知道了....$]],},
{[1] = [[profile.activity = '正常']],[2] = [[状态记录]],[3] = {44},[4] = 1,[5] = [[^一股阴冷的浓雾突然出现，很快地包围了你。$]],},
{[1] = [[profile.buff['qishang'] = true]],[2] = [[状态记录]],[3] = {45},[4] = 1,[5] = [[^你只觉肩头云门穴微微一痛，脑中微感眩晕。$]],},
{[1] = [[state.buff["yunu-xinjing_suxin"] = nil]],[2] = [[状态记录]],[3] = {46},[4] = 1,[5] = [[^你玉女心经心法渐渐散去，神情逐渐恢复常态。$]],},
{[1] = [[state.buff["linji-zhuang_daxiao"] = true]],[2] = [[状态记录]],[3] = {47},[4] = 1,[5] = [[^你屏息静气，交错运行大小二庄，只觉一股暖流出天门，穿地户，沿着全身经脉运行一周，汇入丹田气海。$|^你已经运功调节精气大小了。$]],},
{[1] = [[state.buff["xuantian-wuji_wuji"] = true]],[2] = [[状态记录]],[3] = {48},[4] = 1,[5] = [[^你将玄天无极功第\S+层功力充塞全身。$]],},
{[1] = [[state.buff["shachang-dianbing_charge"] = true]],[2] = [[状态记录]],[3] = {49},[4] = 1,[5] = [[^你大手向前一挥，大吼一声：兔崽子们，跟老子一起冲啊。$|^你的手下正在冲锋中。$]],},
{[1] = [[state.buff["bitao-xuangong_yixing"] = true]],[2] = [[状态记录]],[3] = {50},[4] = 1,[5] = [[^你脸上青气大盛，脚下缓缓踩著九宫八卦方位，头顶冒出腾腾白气，四面隐隐传来潮涌之声，碧涛玄功已发挥到极致！$|^你正在运用「移形换位」心法！$]],},
{[1] = [[state.buff["yunu-xinjing_suxin"] = true]],[2] = [[状态记录]],[3] = {51},[4] = 1,[5] = [[^只见你微微一笑，神情安宁，眼中竟似没有他人一样。$|^你已经在运用素心诀了。$]],},
{[1] = [[state.buff["lengyue-shengong_yue"] = nil]],[2] = [[状态记录]],[3] = {52},[4] = 1,[5] = [[^你的冷月神功运行完毕，将内力收回丹田。$]],},
{[1] = [[profile.activity = '死亡']],[2] = [[状态记录]],[3] = {53},[4] = 1,[5] = [[^鬼门关 - $]],},
{[1] = [[state.buff["dulong-dafa_powerup"] = nil]],[2] = [[状态记录]],[3] = {54},[4] = 1,[5] = [[^只见你额头汗水有如泉涌，呼呼喘气，显得疲累不堪。$]],},
{[1] = [[state.buff["dulong-dafa_powerup"] = true]],[2] = [[状态记录]],[3] = {55},[4] = 1,[5] = [[^只见你高声叫道：“洪教主万年不老，永享仙福，寿与天齐！”$]],},
{[1] = [[state.buff["shachang-dianbing_powerup"] = nil]],[2] = [[状态记录]],[3] = {56},[4] = 1,[5] = [[^你的沙场战嚎运行完毕，将内力收回丹田。$]],},
{[1] = [[state.buff["beiming-shengong_shield"] = nil]],[2] = [[状态记录]],[3] = {57},[4] = 1,[5] = [[^你的北冥护体神功运行完毕，将内力收回丹田。$]],},
{[1] = [[state.buff["linji-zhuang_zhixin"] = true]],[2] = [[状态记录]],[3] = {58},[4] = 1,[5] = [[^你微一凝神，运动之心两庄，去浊气出体外，收清气入心中，只觉灵台清明，领悟力似乎有所增加。$|^你已经运用之心二庄凝聚心神了。$]],},
{[1] = [[invalid_ask_ping()]],[2] = [[状态记录]],[3] = {59},[4] = 1,[5] = [[^平一指说道：上次你吃的药药性未过，不能重复吃药。$|^你吃下大力丸之后，顿时感觉百病全消。$]],},
{[1] = [[state.buff["lengyue-shengong_yue"] = true]],[2] = [[状态记录]],[3] = {60},[4] = 1,[5] = [[^你潜运冷月心法，一股至阴的内劲自丹田而生游走全身经脉。$]],},
{[1] = [[state.buff["huntian-qigong_shengang"] = nil]],[2] = [[状态记录]],[3] = {61},[4] = 1,[5] = [[^你的混天气功运行完毕，将内力收回丹田，\S+上的淡光亦消失无踪。$]],},
{[1] = [[state.buff["shachang-dianbing_charge"] = nil]],[2] = [[状态记录]],[3] = {62},[4] = 1,[5] = [[^你停止了冲锋指挥。$]],},
{[1] = [[state.buff["linji-zhuang_fengyun"] = nil]],[2] = [[状态记录]],[3] = {63},[4] = 1,[5] = [[^你风云行功已久，略觉步履沉重了一些。$]],},
{[1] = [[state.buff["xuantian-wuji_wuji"] = nil]],[2] = [[状态记录]],[3] = {64},[4] = 1,[5] = [[^过了片刻，你将玄天无极神功气聚丹田，深吸了一口气。$|^你内息变换，运转的玄天无极功顿时瓦解。$]],},
{[1] = [[valid_force_yun()]],[2] = [[状态记录]],[3] = {65},[4] = 1,[5] = [[^你已经在运功中了。$]],},
{[ [[Enable]] ] = true,},
{[ [[Enable]] ] = true,},
{[ [[Enable]] ] = true,},
{[ [[Enable]] ] = true,},
{[ [[Enable]] ] = true,},
{[ [[Enable]] ] = true,},
{[ [[Enable]] ] = true,},
{[ [[Enable]] ] = true,},
{[ [[Enable]] ] = true,},
{[ [[Enable]] ] = true,},
{[ [[Enable]] ] = true,},
{[ [[Enable]] ] = true,},
{[ [[Enable]] ] = true,},
{[ [[Enable]] ] = true,},
{[ [[Enable]] ] = true,},
{[ [[Enable]] ] = true,},
{[ [[Enable]] ] = true,},
{[ [[Enable]] ] = true,},
{[ [[Enable]] ] = true,},
{[ [[Enable]] ] = true,},
{[ [[Enable]] ] = true,},
{[ [[Enable]] ] = true,},
{[ [[Enable]] ] = true,},
{[ [[Enable]] ] = true,},
{[ [[Enable]] ] = true,},
{[ [[Enable]] ] = true,},
{[ [[Enable]] ] = true,},
{[ [[Enable]] ] = true,},
{[ [[Enable]] ] = true,},
{[ [[Enable]] ] = true,},
{[ [[Enable]] ] = true,},
{[ [[Enable]] ] = true,},
}